name: HTTP Config Enricher
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: input_topic
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write to.
    defaultValue: output_topic
  - name: POSTGRES_HOST
    inputType: FreeText
    description: The PostgreSQL host to connect to.
    required: true
  - name: POSTGRES_PORT
    inputType: FreeText
    description: The PostgreSQL port to connect to.
    defaultValue: 80
    required: true
  - name: POSTGRES_USER
    inputType: FreeText
    description: The PostgreSQL user to connect with.
    defaultValue: admin
    required: true
  - name: POSTGRES_PASSWORD
    inputType: Secret
    description: The PostgreSQL password to connect with.
    defaultValue: postgresql_password
    required: true
  - name: POSTGRES_DBNAME
    inputType: FreeText
    description: The PostgreSQL database to connect to.
    defaultValue: quix
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
