name: InfluxDB2
language: docker
variables:
  - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    inputType: Secret
    description: Default Admin Token to initialize Influx with
    defaultValue: influxdb_admin_token
    required: true
  - name: DOCKER_INFLUXDB_INIT_PASSWORD
    inputType: Secret
    description: Default Admin password to initialize Influx with
    defaultValue: influxdb_admin_password
    required: true
  - name: DOCKER_INFLUXDB_INIT_BUCKET
    inputType: FreeText
    description: Bucket Name to initialize Influx with
    defaultValue: my_bucket
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: influxdb2